Add LibrarySystem Project
tihomirpmg/LibrarySystem pull request #1
Opened 2022-03-29 12:45 UTC by tihomirpmg

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystems/Shared/NavMenu.razor
> +@code {
C# кода и HTML кода не са раделени в отделни файлове.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystem.Bussines/Repos/LibraryBookRepository.cs
> +            //libraryBook.CreatedDate = DateTime.Now;
Ако този код няма да се ползва е по-добре да се махне.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystem.Bussines/Repos/SectionRepository.cs
> +                throw new RepositoryException("Section cannot be updated.");
Тук е хубаво да се подава и самата грешка, за да има по-точна информация какво точно е гръмнало.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystem.Bussines/Repos/TitleRepository.cs
> +            return 0;
Тук връщаш число, което не се ползва никъде по другите слоеве. Методите за изтриване е добре да имат return type - void.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystem.Bussines/Repos/TitleRepository.cs
> +using System.Linq;
Има излишни using-и, може да ги махнеш, ако няма да се ползват.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystem.Bussines/Repos/TitleRepository.cs
> +        public async Task<TitleDTO> IsBookUnique(string name, int bookId = 0)
Каква е идеята на този метод? Според името му разбирам, че се пита дали книгата е уникална, а в същото време не връща булева променлива.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystems/Areas/Identity/Pages/Account/LogOut.cshtml
> +﻿@page
Веднъж имаш папка Areas, в която имаш само неща свързани с акаунта. Отделно имаш папка pages на първо ниво, където пък са ти останалите области, свързани с библиотеката, което е малко подвеждащо. Ако си решил да слагаш Areas, то всички области трябва да са подпапки в папката Areas, а не само нещата свързани с акаунта.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystems.sln
> +﻿
Името на solution-а, както и на проекта с уеба е добре да бъде в единствено число, защото става дума за една библиотечна система, не за много такива.

2022-04-04 05:55 UTC, dilqnatoteva1992 commented on LibrarySystems/LibrarySystems.csproj
> +<Project Sdk="Microsoft.NET.Sdk.Web">
Хубаво е да се добави един README.md файл, в който да са описани стъпките за конфигурация на проекта и стартирането му. Също и описание на проекта(напр. за какво служи?).

2022-05-17 07:03 UTC, vdachev requested changes
Привет. Ето и малко коментари от мен.

2022-05-17 07:03 UTC, vdachev commented on README.md
> -# LibrarySystem
Привет. С известно закъснение, започвам с малко коментари и аз.

Заглавието по-скоро би трябвало да бъде "Library System". Самият файл не е коректно форматиран, като:

- Неправилно са използвани headings за неща, които по същество не са заглавия.
- Параграфите не са отделени.
- При единия heading липсва интервал, който го прави синтактично некоректен от гледна точка на Markdown.
- Имената на файловете следва да са italic, а кодът да се цитира по съответния начин (в частност connection string, идентификатори и т.н.).

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem/wwwroot/css/bootstrap/bootstrap.min.css
> +/*!
Ако използваш външни библиотеки и въобще ресурси (изображения, шрифтове и т.н.), можеш да ги реферираш от CDN, вместо да ги вкарваш като част от проекта тук. Друг вариант е да използваш [LibMan](https://docs.microsoft.com/en-us/aspnet/core/client-side/libman/libman-vs?view=aspnetcore-6.0).

Идеята е, че няма смисъл в хранилището да стоят ресурси, които се управляват съвсем другаде и проследяването на промените в които е безпредметно.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem/wwwroot/css/styles.css
> +.page[b-rii106usbr] {
Виждам, че тук в този CSS се споменават доста атрибути, които обаче се генерират на произволен принцип. При следваща компилация този CSS може въобще да не сработи. В този смисъл, хубаво е да намериш по-устойчив метод за стилизиране на съответните HTML елементи.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem/wwwroot/css/styles.css
> +.page[b-rii106usbr] {
Моя грешка. Изглежда този файл се генерира автоматично от CSS на съответните компоненти. Като повечето автоматично генерирани файлове, този в такъв случай не трябва да е в хранилището и, съответно, следва да е описан в *.gitignore*.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem/appsettings.Development.json
> +{
Хубаво би било да има и един *appsettings.Production.json*, тъй като иначе този проект няма как да бъде конфигуриран в продукционна среда, без някой да си го съчини.

2022-05-17 07:03 UTC, vdachev commented on README.md
> +
По задание, тук трябва да има кратко описание на проекта, имена и имейл на автора.

2022-05-17 07:03 UTC, vdachev commented on README.md
> +DefaultConnection in appsettings.json with "DefaultConnection": "Server=.;Database=LibrarySystem;Trusted_Connection=True;MultipleActiveResultSets=true"
По задание е добре да има инструкции за компилиране и инсталиране на приложението.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem/Shared/LoginDisplay.razor
> +@code {
Защо е необходимо наличието на `@code` секция?

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Data/Migrations/20220321153622_CreateDatabase.cs
> +﻿using System;
Тъй като това е първоначална версия на приложението, мисля, че няма смисъл да има повече от една миграция. Върви при нова версия (напр. нов Pull Request) да има нова миграция (ако е необходимо).

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Mapper/MappingProfile.cs
> +﻿using AutoMapper;
Честно казано, практиката при нас показва, че използването на *AutoMapper* по-скоро може да доведе до грешки, отколкото да улесни живота. По-лесно за debugging (макар и с малко повече код) е да се използват статични методи за конвертиране между типовете.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Mapper/MappingProfile.cs
> +            CreateMap<TitleDTO, Title>();
Виждам, по-горе `DTo`, тук - `DTO`, а всъщност конвенцията твърди, че при съкращение от три или повече символа, трябва да се използва Pascal case, т.е. `Dto`.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/IImagesRepository.cs
> +        public Task<int> CreateNewImage(ImagesDTO imageDTO);
Добра практика при асинхронните методи е:
- имената да завършват със суфикс `Async`, напр. `CreateNewImageAsync`;
- да приемат като последен optional параметър `CancellationToken`, който да се предава към асинхронните методи навътре.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/IImagesRepository.cs
> +namespace LibrarySystem.Bussines.Repos.IRepository
`IRepositority` е подходящо име за интефейс, но не и за namespace. Въобще, разполагането на тези repositories тук е малко излишно.

Ако целта е да наследяват общ интерфейс (което въобще не е лошо), то такъв интерфейс е хубаво да има, а не namespace.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/IImagesRepository.cs
> +        public Task<int> CreateNewImage(ImagesDTO imageDTO);
Може би имаш предвид един image, т.е. `ImageDto`.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/ILibraryBookRepository.cs
> +
Тук има излишен празен ред. Прави впечатление, че при други repositories има празен ред между методите (което е по-пригледно).

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/ILibraryBookRepository.cs
> +        public void DeleteBook(int bookId);
Не виждам причина този метод да не е асинхронен.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/ILibraryBookRepository.cs
> +        public Task<LibraryBookDTo> UniqueBook(string name, int bookId=0);
Тук, освен че нещо не е сработило подравняването (Ctrl+K+D), името на метода не следва конвенцията да започва с глагол. Всъщност, с това наименование, не става много ясно какво прави този метод.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/IImagesRepository.cs
> +        public Task<int> CreateNewImage(ImagesDTO imageDTO);
Добре е видимите (т.е. тези, които не са `private` или `internal`) типове (интерфейси и класове), свойства, полета и т.н. да са документирани с XML документация, така че този, който позлва съответната библиотека да е наясно с методите.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Common/Details.cs
> +        public const string Role_Admin = "Admin";
.NET Naming Convension не предполага използванетона underscore (подчертавка) в идентифкаторите.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Common/Details.cs
> +    public static class Details
Наименованието на този тип е неподходящо - според мен `RoleNames` ще му отива повече. Съответно, константите в него могат да имат имена като `Admin`, `Librarian` и т.н.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/RepositoryException.cs
> +        public RepositoryException(string message, Exception innerException) : base(message, innerException)
За пригледност е добре `: base(...)` да се пренесе на следващия ред с един tab навътре.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/RepositoryException.cs
> +    public class RepositoryException : Exception
Хубаво е да се имплементират всички базови конструктори на exception и особено default-ния.

2022-05-17 07:03 UTC, vdachev commented on LibrarySystem.Bussines/RepositoryException.cs
> +        public RepositoryException(string message, Exception innerException) : base(message, innerException)
Добре е между методи, полета и т.н. да има празни редове.

2022-05-26 12:32 UTC, vdachev commented on README.md
> -# LibrarySystem
Между другото, правят ми впечатление и следните неща:
- Проектите са на .NET 5. Предлагам ти да ги мигрираш на .NET 6.
- Думата "business" е написана като "bussines", което грешно.

2022-05-26 12:35 UTC, vdachev commented on LibrarySystem.Bussines/Repos/IRepository/IImagesRepository.cs
> +namespace LibrarySystem.Bussines.Repos.IRepository
Хубаво си махнал този namespace, но това означава и че трябва да изместиш файловете в съответната директория.

Също така, прави впечатление, че си направил отделен интерфейс за всеки тип обект, което само по себе си не е лошо, но е хубаво тези интерфейси да наследяват някакъв общ `IRepository<T>` с общите за това методи, напр. `GetById`, `Create`, `Update`, `Delete`  и т.н., докато `IImageRepository` (например) да наследява `IRepository<ImageDto>`, но да добавя в себе си и методите специфични за изображенията.

2022-07-06 06:48 UTC, vdachev requested changes
Като допълнение към останалите коментари, картинките с кориците на книгите нямат място в repository. Можеш да си ги регистрираш с някакви линкове от нета. Ако пък пълниш базата с тях при инициализация, би трябвало да са в папката с данните за инициализация.

2022-07-06 06:48 UTC, vdachev commented on README.md
> +DefaultConnection in appsettings.json with "DefaultConnection": "Server=.;Database=LibrarySystem;Trusted_Connection=True;MultipleActiveResultSets=true"
Документацията продължава да не е добре форматиран Markdown. Запознай се с правилата за писане на Markdown.
Също, имаше предходен коментар, който казвааше, че имената на файловете трябва да са _italic_, а и парчетата код следва да са форматирани като такива.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem/LibrarySystem.csproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
*.user файловете нямат място в repository и следва да са игнорирани в *.gitignore*.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem/Areas/Title/TitleUpsert.razor
> +    <h3 class="card-title text-info mb-3 ml-3">@Create Book</h3>
Какво се очаква да прави `@Create Book`. Този `@` ме притеснява.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem/Areas/Identity/Pages/Account/LogOut.cshtml
> +﻿@page
Има разминаване между имената на файловете *LogOut.cshtml* и *Logout.cshtml.cs*. Под файлови системи, в които размерът на буквите има значение (разбирай, всички различни от специфичните за Windows), това би направило проблем.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem.Models/LibraryBookDto.cs
> +        public LibraryBookDTo()
Този контролер е доста излишен.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem.Data/Data/Section.cs
> +    using LibrarySystem.Models;
`using` е по-добре да са в началото на файла, преди `namespace`. Още повече, че в C# 10.0 можеш да използваш file-scoped namespaces.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem.Bussines/Repos/TitleRepository.cs
> +using System.Linq;
Нещо повече, хубаво е `System.` using-ите да са в началото, за което има настройка във Visual Studio.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem/Shared/MainLayout.razor
> +            <a href="https://docs.microsoft.com/aspnet/" target="_blank">About</a>
Този линк тук е малко излишен май.

2022-07-06 06:48 UTC, vdachev commented on LibrarySystem/Shared/LoginDisplay.razor
> +            <a href="Identity/Account/Register">Register</a>
Не съм убеден, че точно това е начинът да се сглобяват линковете към страниците. За целта има `NavLink` компонент, `NavMenu` и т.н.

2022-07-14 06:39 UTC, tihomirpmg commented on LibrarySystem/Areas/Title/TitleUpsert.razor
> +    <h3 class="card-title text-info mb-3 ml-3">@Create Book</h3>
Здравей, ами този @Create има променлива стойност и затова е така, ако се добавя нова книга на бутона пише "Create", а ако се прави промяна по книга, която вече е добавена, този @Create се променя на "Update" в Edit формата.

2022-08-03 05:20 UTC, merged